### PR TITLE
Make web UI dependencies optional

### PR DESCRIPTION
**Pull request by cthoyt**
## Update text

This PR makes the UI for the gilda web app optional. This means you don't have to install the `flask-bootstrap` or `flask-wtf` dependencies by default. If these aren't available, the home page just redirects to the apidocs.

These changes were made after the original PR (see text below) due to comment in https://github.com/indralab/gilda/pull/119#issuecomment-1620099158.

## Original Text

There are several situations in which installing the web dependencies for Gilda by default is inconvenient. The largest are due to conflicts in versions of werkzeug (which is pinned in gilda) and conflicts between flask-bootstrap (the one gilda uses, but it's abandoned) and bootstrap-flask (fork other former and is currently maintained)

As it is, it's not possible to easily have gilda simultaneously installed with biomappings, and this is a concrete issue for someone who might want to contribute some curations (without doing some more manual dependency management)

This PR simply makes the web dependencies optional. It updates the dockerfile and tests to make sure these are still installed where necessary, and updates relevant documentation accordingly

### CODE REVIEW

**Comment by bgyori** [comment]
Honestly, I saw this coming years ago. At the time I felt strongly that Gilda should have a default, built in REST API that can be run locally without any extra dependencies. The issue with problematic additional dependencies is why I didn't want to mix that up with UI elements. So the solution I'd ideally be looking for is the combination is a (1) non-optional programmatic REST API and (2) optional UI elements. Is that possible using either two different modules for web services (that might still reuse some code) or some kind of blueprint-based setup?

**Comment by bgyori** [comment]
See e.g., https://github.com/indralab/gilda/pull/41#issuecomment-763297165

**Comment by cthoyt** [comment]
@bgyori I managed to make the UI optional. If it's flagged to not use the UI or the UI dependencies aren't available, then the home page will automatically redirect to api docs page.

**Comment by cthoyt** [comment]
@bgyori one last thing - can we unrestrict the werkzeug version? The commit where this restriction was added https://github.com/indralab/gilda/commit/2a576de10f359d40c0afdb13c4ab844a6a182141 doesn't seem to have an explanation of why it was done

**Review by bgyori — APPROVED** [review]
Works great, thanks!

**Pull request merged**
